server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitoring.anand-test.l-free-machine.emulab.net:3100/loki/api/v1/push

scrape_configs:
  - job_name: l-free-machine
    static_configs:
      - targets:
          - localhost
        labels:
          job: l-free-machine
          app: l-free-machine
          __path__: ./logs/*.log
