global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "l-free-machine"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "broker1.anand-test.l-free-machine.emulab.net:8083"
          - "broker2.anand-test.l-free-machine.emulab.net:8083"
        labels:
          role: broker

      - targets:
          - "server1.anand-test.l-free-machine.emulab.net:8083"
          - "server2.anand-test.l-free-machine.emulab.net:8083"
          - "server3.anand-test.l-free-machine.emulab.net:8083"
          - "server4.anand-test.l-free-machine.emulab.net:8083"
          - "server5.anand-test.l-free-machine.emulab.net:8083"
          - "server6.anand-test.l-free-machine.emulab.net:8083"
          - "server7.anand-test.l-free-machine.emulab.net:8083"
          - "server8.anand-test.l-free-machine.emulab.net:8083"
        labels:
          role: server
